# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jj2PbrixBxbNJ3BSlQN2trM3AXviGk93
"""

class Room:
    def __init__(self, room_number, room_type, is_booked=False):
        self.room_number = room_number
        self.room_type = room_type
        self.is_booked = is_booked
        self.next = None

class HotelManagementSystem:
    def __init__(self):
        self.head = None

    def add_room(self, room_number, room_type):
        new_room = Room(room_number, room_type)
        if self.head is None:
            self.head = new_room
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_room

    def book_room(self, room_number):
        current = self.head
        while current:
            if current.room_number == room_number:
                if not current.is_booked:
                    current.is_booked = True
                    print(f"Room {room_number} has been booked.")
                    return
                else:
                    print(f"Room {room_number} is already booked.")
                    return
            current = current.next
        print(f"Room {room_number} not found.")

    def cancel_booking(self, room_number):
        current = self.head
        while current:
            if current.room_number == room_number:
                if current.is_booked:
                    current.is_booked = False
                    print(f"Booking for room {room_number} has been canceled.")
                    return
                else:
                    print(f"Room {room_number} is not currently booked.")
                    return
            current = current.next
        print(f"Room {room_number} not found.")

    def display_rooms(self):
        current = self.head
        if not current:
            print("No rooms available.")
            return
        while current:
            status = "Booked" if current.is_booked else "Available"
            print(f"Room {current.room_number} - Type: {current.room_type} - Status: {status}")
            current = current.next

    def search_available_rooms(self, room_type):
        current = self.head
        found = False
        while current:
            if current.room_type == room_type and not current.is_booked:
                print(f"Available Room {current.room_number} - Type: {current.room_type}")
                found = True
            current = current.next
        if not found:
            print(f"No available rooms of type {room_type}.")

    def search_room_by_number(self, room_number):
        current = self.head
        while current:
            if current.room_number == room_number:
                status = "Booked" if current.is_booked else "Available"
                print(f"Room {room_number} - Type: {current.room_type} - Status: {status}")
                return
            current = current.next
        print(f"Room {room_number} not found.")

def main():
    hotel = HotelManagementSystem()

    # Adding rooms
    hotel.add_room(101, "Single")
    hotel.add_room(102, "Double")
    hotel.add_room(103, "Suite")
    hotel.add_room(104, "Single")
    hotel.add_room(105, "Double")
    hotel.add_room(106, "single")
    hotel.add_room(107, "Double")
    hotel.add_room(108, "Double")
    hotel.add_room(109, "furnished")
    hotel.add_room(110, "Double")
    hotel.add_room(111, "Double")
    hotel.add_room(112, "suite")
    hotel.add_room(113, "Double")
    hotel.add_room(114, "single")
    hotel.add_room(115, "Double")
    hotel.add_room(116, "Double")
    hotel.add_room(117, "single")
    hotel.add_room(118, "Double")

    while True:
        print("\n--- Hotel Management System ---")
        print("1. Display all rooms")
        print("2. Book a room")
        print("3. Cancel a booking")
        print("4. Search available rooms by type")
        print("5. Search room by number")
        print("6. Exit")

        choice = input("Enter your choice (1-6): ").strip()

        if choice == "1":
            hotel.display_rooms()
        elif choice == "2":
            room_number = int(input("Enter the room number to book: ").strip())
            hotel.book_room(room_number)
        elif choice == "3":
            room_number = int(input("Enter the room number to cancel booking: ").strip())
            hotel.cancel_booking(room_number)
        elif choice == "4":
            room_type = input("Enter the room type to search for (e.g., Single, Double): ").strip()
            hotel.search_available_rooms(room_type)
        elif choice == "5":
            room_number = int(input("Enter the room number to search: ").strip())
            hotel.search_room_by_number(room_number)
        elif choice == "6":
            print("Exiting the system.")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 6.")

if __name__ == "__main__":
    main()